# Base Rules
$center-float-large = class:^(center-float-large)$|^(.*Geeqie.*)$|^(.*geeqie.*)$|^(.*celluloid.*)$|^(.*mpv.*)$|^(.*File Upload.*)$|^(.*imv.*)$
windowrule = float, $center-float-large
windowrule = size 70% 70%, $center-float-large
windowrule = center 1, $center-float-large

$center-float = class:^(center-float)$|^(.*file-roller.*)$|^(.*FileRoller.*)$|^(.*blueman-manager.*)$|^(.*blueberry.py.*)$
$center-float-title = title:^(.*Open Folder.*)$|^(.*Open File.*)$|^(.*Save File.*)$|^(.*Save Folder.*)$|^(.*Save Image.*)$|^(.*Library.*)$|^(.*Save As.*)$|^(.*Open As.*)$|^(.*Volume Control.*)$|^(.*Settings.*)$|^(.*Warning.*)$|^(.*nmtui.*)$|^(update.sh)$
windowrule = float, $center-float
windowrule = float, $center-float-title
windowrule = size 50% 50%, $center-float
windowrule = size 50% 50%, $center-float-title
windowrule = center 1, $center-float
windowrule = center 1, $center-float-title

$center-float-mini = class:^(center-float-mini)$|^(.*galculator.*)$|^(.*ytdlp-gui.*)$
windowrule = float, $center-float-mini
windowrule = size 30% 40%, $center-float-mini
windowrule = center 1, $center-float-mini

# Float rules
windowrule = float, class:xfce-polkit|class:file_progress|class:confirm|class:dialog|class:download|class:notification|class:error|class:splash|class:confirmreset|class:wleave|class:nwg-look|class:nm-connection-editor|class:Picture-in-Picture
windowrule = float, title:branchdialog|title:Picture-in-Picture
windowrule = size 30% 30%, title:^(Picture-in-Picture)$
windowrule = suppressevent maximize, class:.*

# Steam Rules
windowrule = minsize 1 1, title:^()$, class:^(steam)$
windowrule = size 30% 60%, title:^(Friends List)$
windowrule = float, title:^(Friends List)$
windowrule = float, class:floorp, title:Picture-in-Picture
#windowrule = float, class:librewolf, title:Picture-in-Picture

# Specific rule for your terminal
windowrule = float, class:^(kitty)$
windowrule = size 40% 50%, class:^(kitty)$

# Specific rule for Rofi
windowrule = float, title:^(.*drun.*)$
windowrule = float, title:^(.*rofi.*)$
windowrule = float, title:^(.*drun.*)$
windowrule = float, title:^(.*rofi.*)$

windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrule = noanim, class:^(xwaylandvideobridge)$
windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrule = noblur, class:^(xwaylandvideobridge)$

# Veskdesktop on workspace 10
windowrule = workspace 10, class:vesktop
windowrule = workspace 10, class:discord

# Firefox/Librewolf on workspace 2
windowrule = workspace 2, class:firefox
windowrule = workspace 2, class:librewolf

#combat master tearing
general {
    allow_tearing = true
}
windowrule = immediate, class:^CombatMaster.x86_64$
general {
    allow_tearing = false
}

windowrule = immediate, class:^(steam_app_230410)$
windowrule = move 0 0, class:^(gamescope)$
windowrule = size 4566 1080, class:^(gamescope)$
windowrule = float, class:^(gamescope)$
#windowrule = stayfocused, class:^(gamescope)$
windowrule = monitor HDMI-A-1, class:^(gamescope)$
windowrule = workspace name:gamescope, class:^(gamescope)$
#windowrule = tag +unfocused, class:^(gamescope)$

windowrule = float, class:^(xdg-desktop-portal-gtk)$
windowrule = float, class:librewolf, title:^(Extension: .*)$
windowrule = workspace 3, class:librewolf, title:Picture-in-Picture