Net/ThemeName "NovaOS-nord"
Net/IconThemeName "ePapirus-Dark"
Gtk/CursorThemeName "Dot-Light"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintmedium"
Xft/RGBA "rgb"
